# -*- coding: UTF-8 -*-

DC_LANGUAGE = [
   (" ", u" "),
   ("bur", u"bur"),
   ("chi", u"chi"),
   ("dut", u"dut"),
   ("eng", u"eng"),
   ("fre", u"fre"),
   ("ger", u"ger"),
   ("gre", u"gre"),
   ("hin", u"hin"),
   ("ind", u"ind"),
   ("jpn", u"jpn"),
   ("khm", u"khm"),
   ("kor", u"kor"),
   ("por", u"por"),
   ("rus", u"rus"),
   ("spa", u"spa"),
   ("thi", u"thi"),
   ("tib", u"tib"),
]
DC_TYPE = [
   (" ", u" "),
   ("Dataset", u"Dataset"),
   ("Event", u"Event"),
   ("Image", u"Image"), 
   ("Interactive", u"Interactive"),
   ("Physical_Object", u"Physical Object"),
   ("Software", u"Software"),
   ("Sound", u"Sound"),
   ("Text", u"Text"),
]
DC_FORMAT = [
   (" ", u" "),
   ("Application", u"Application"),
   ("Audio", u"Audio"),
   ("CD_Rom", u"CD-Rom"),
   ("GIS_Informix", u"GIS-Informix"),
   ("GIS_Oracle", u"GIS-Oracle"),
   ("GIS_SDE", u"GIS-SDE"),
   ("GIS_Spatialware", u"GIS-Spatialware"),
   ("Image", u"Image"),
   ("Message", u"Message"),
   ("Model", u"Model"),
   ("Multipart", u"Multipart"),
   ("Text", u"Text"),
   ("TimeMap Dataset", u"TimeMap Dataset"),
   ("Video", u"Video"),
   ("WWWpages_database_dynamic", u"WWW pages-database/dynamic"),
   ("WWWpages_static", u"WWW pages-static"),
]
ECAI_TEAM = [
   (" ", u" "),
   ("Africa", u"Africa"),
   ("Asian_Religion", u"Asian Religion"),
   ("Australia", u"Australia"),
   ("Austronesia", u"Austronesia"),
   ("British_Isles", u"British Isles"),
   ("Buryatia", u"Buryatia"),
   ("Caucasus", u"Caucasus"),
   ("Central_America", u"Central America"),
   ("Central_Asia", u"Central Asia"),
   ("China", u"China"),
   ("Circumpolar", u"Circumpolar"),
   ("Europe", u"Europe"),
   ("Iberian", u"Iberian"),
   ("Japan", u"Japan"),
   ("Korea", u"Korea"),
   ("Maritime_Buddhism", u"Maritime Buddhism"),
   ("Mediterranean", u"Mediterranean"),
   ("Mexico", u"Mexico"),
   ("None_unknown", u"None or unknown"),
   ("North_American_Religion", u"North American Religion"),
   ("Russia", u"Russia"),
   ("Silk_Road", u"Silk Road"),
   ("South_America", u"South America"),
   ("South_Asia", u"South Asia"),
   ("Southeast_Asia", u"Southeast Asia"),
   ("Southwest_Asia_and_North_Africa", u"Southwest Asia and North Africa"),
   ("Thai", u"Thai"),
   ("Tibet_and_Himalaya", u"Tibet and Himalaya"),
   ("Turkey", u"Turkey"),
   ("U_S_and_Canada", u"U.S. and Canada"),
   ("Western_Europe", u"Western Europe"),
   ("Worldwide", u"Worldwide"),
]
DC_SUBJECT_DOMAIN = [
   (" ", " "),
   ("Administrative_geography", "Administrative geography"),
   ("Archaeology", "Archaeology"),
   ("Art", "Art"),
   ("Biography", "Biography"),
   ("Build_Environment", "Build Environment"),
   ("Demographics", "Demographics"),
   ("Environment_ecology", "Environment/ecology"),
   ("Ethnography", "Ethnography"),
   ("Land_use_agriculture", "Land use/agriculture"),
   ("Language", "Language"),
   ("New_Item", "New Item"),
   ("Other", "Other"),
   ("Physical_geography_GIS", "Physical geography/GIS"),
   ("Political", "Political"),
   ("Religion", "Religion"),
   ("Science_technology", "Science/technology"),
   ("Socioeconomic", "Socioeconomic"),
   ("Trade_routes", "Trade routes"),
   ("Transportation_infrastructure", "Transportation/infrastructure"),
]


